import React, { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BriefcaseBusiness, Globe2, Linkedin, Mail, Menu, Sparkles, UsersRound, X } from 'lucide-react';
import pic1 from '../assets/madam.jpeg';

const navItems = ['home', 'about', 'leadership', 'impact', 'contact'];
const focusAreas = [['Community building', 'Growing spaces where builders connect and collaborate.'], ['Education & training', 'Equipping talent with practical, future-ready Web3 skills.'], ['Global partnerships', 'Linking local ambition with international opportunity.']];
const impacts = [['Blockchain adoption', 'Making blockchain practical for East African businesses, from SMEs to enterprises.'], ['Talent development', 'Creating training and mentorship routes into the global Web3 ecosystem.'], ['Financial inclusion', 'Supporting inclusive solutions for underserved communities across the region.']];

const XIcon = ({ size = 20 }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" /></svg>;
const Heading = ({ eyebrow, title, copy }) => <div className="max-w-2xl"><p className="mb-4 text-xs font-bold uppercase tracking-[.23em] text-amber-400">{eyebrow}</p><h2 className="text-4xl font-semibold tracking-[-.045em] text-white sm:text-5xl">{title}</h2>{copy && <p className="mt-5 text-base leading-7 text-zinc-400 sm:text-lg">{copy}</p>}</div>;

export default function Portfolio() {
  const [menu, setMenu] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [active, setActive] = useState('home');
  useEffect(() => {
    const handleScroll = () => { setScrolled(window.scrollY > 24); const current = navItems.find((id) => { const el = document.getElementById(id); if (!el) return false; const r = el.getBoundingClientRect(); return r.top <= 160 && r.bottom > 160; }); if (current) setActive(current); };
    handleScroll(); window.addEventListener('scroll', handleScroll, { passive: true }); return () => window.removeEventListener('scroll', handleScroll);
  }, []);
  const go = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); setMenu(false); };
  const NavButtons = ({ mobile = false }) => <>{navItems.map((item) => <button key={item} onClick={() => go(item)} className={mobile ? `rounded-xl px-4 py-3 text-left text-sm font-medium capitalize ${active === item ? 'bg-amber-400 text-zinc-950' : 'text-zinc-300 hover:bg-white/5'}` : `rounded-full px-4 py-2 text-sm capitalize transition-colors ${active === item ? 'bg-white/10 text-amber-300' : 'text-zinc-400 hover:text-white'}`}>{item}</button>)}</>;
  return <div className="min-h-screen overflow-x-hidden bg-[#09090b] text-zinc-100 selection:bg-amber-400 selection:text-zinc-950">
    <div className="pointer-events-none fixed inset-0 -z-0 overflow-hidden"><div className="absolute -left-40 top-0 h-[34rem] w-[34rem] rounded-full bg-amber-400/[.07] blur-3xl" /><div className="absolute right-[-16rem] top-[38rem] h-[34rem] w-[34rem] rounded-full bg-orange-500/[.06] blur-3xl" /></div>
    <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${scrolled ? 'border-b border-white/10 bg-zinc-950/85 shadow-2xl shadow-black/20 backdrop-blur-xl' : 'bg-transparent'}`}><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10">
      <button onClick={() => go('home')} className="group flex items-center gap-3 text-left" aria-label="Go to home"><span className="grid h-10 w-10 place-items-center rounded-full bg-amber-400 text-zinc-950 transition group-hover:rotate-12"><Sparkles size={18} /></span><span><span className="block text-sm font-bold text-white">Sarah Wahinya</span><span className="block text-[10px] font-medium uppercase tracking-[.18em] text-zinc-500">Web3 & ecosystems</span></span></button>
      <nav className="hidden items-center gap-1 lg:flex" aria-label="Main navigation"><NavButtons /></nav><div className="hidden items-center gap-2 sm:flex"><a className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-zinc-300 transition hover:border-amber-400/60 hover:text-amber-300" href="https://linkedin.com/in/sarah-wahinya" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={17} /></a><a className="inline-flex h-10 items-center gap-2 rounded-full bg-amber-400 px-4 text-sm font-bold text-zinc-950 transition hover:bg-amber-300" href="mailto:sarahwahinya1@gmail.com">Let’s talk <ArrowUpRight size={16} /></a></div><button className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-white lg:hidden" onClick={() => setMenu(!menu)} aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu}>{menu ? <X size={20} /> : <Menu size={21} />}</button></div>
      {menu && <nav className="border-t border-white/10 bg-zinc-950 px-5 py-4 shadow-2xl lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-7xl gap-1"><NavButtons mobile /></div></nav>}</header>
    <main className="relative z-10">
      <section id="home" className="mx-auto flex min-h-[100svh] max-w-7xl items-center px-5 pb-16 pt-28 sm:px-8 lg:px-10"><div className="grid w-full items-center gap-12 lg:grid-cols-[1.08fr_.92fr] lg:gap-20"><div className="order-2 lg:order-1"><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.21em] text-amber-400"><span className="h-px w-8 bg-amber-400" />Building from East Africa</p><h1 className="max-w-3xl text-5xl font-semibold leading-[.96] tracking-[-.065em] text-white sm:text-6xl md:text-7xl">Connecting African talent to the <span className="text-amber-400">world stage.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-400 sm:text-xl">Sarah Wahinya is a blockchain ecosystem leader creating inclusive pathways for African builders, businesses, and communities to thrive in Web3.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={() => go('contact')} className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-amber-400 px-6 text-sm font-bold text-zinc-950 transition hover:bg-amber-300">Start a conversation <ArrowUpRight size={17} /></button><button onClick={() => go('about')} className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-white/15 px-6 text-sm font-semibold text-white transition hover:border-white/40 hover:bg-white/5">Discover the work <ArrowDownRight size={17} /></button></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-4 border-t border-white/10 pt-6 text-sm"><span className="text-zinc-500">President <b className="ml-1 font-semibold text-zinc-200">Stellar East Africa</b></span><span className="text-zinc-500">Founder <b className="ml-1 font-semibold text-zinc-200">Zu’Co Ltd</b></span></div></div><div className="order-1 mx-auto w-full max-w-sm sm:max-w-md lg:order-2 lg:max-w-none"><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem] border border-white/10 bg-zinc-900 p-2 shadow-2xl shadow-black/40 sm:rounded-[2.5rem]"><img src={pic1} alt="Sarah Wahinya" className="h-full w-full rounded-[1.5rem] object-cover object-center grayscale-[12%]" /><div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-white/15 bg-zinc-950/80 p-4 backdrop-blur-md"><p className="text-xs font-bold uppercase tracking-[.17em] text-amber-400">Ecosystem architect</p><p className="mt-1 text-sm text-zinc-200">Enabling the next generation of African Web3 leadership.</p></div></div></div></div></section>
      <section id="about" className="scroll-mt-20 border-y border-white/10 bg-white/[.025] px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-24"><Heading eyebrow="01 — About" title="A more connected, capable digital Africa." copy="A conviction that innovation works best when the people closest to the challenge help shape the solution." /><div className="space-y-6 text-base leading-8 text-zinc-400 sm:text-lg"><p>As President of Stellar East Africa and Founder of Zu’Co Ltd, Sarah bridges African innovation with global Web3 opportunity. Her work is grounded in practical education, meaningful partnerships, and community-led growth.</p><p>She creates spaces where African talent can do more than participate in the digital economy—they can lead it. Every program and partnership is designed to make the next step more accessible.</p><div className="grid gap-3 pt-3 sm:grid-cols-3">{[[Globe2, 'Global perspective'], [UsersRound, 'Community first'], [Sparkles, 'Impact led']].map(([icon, label]) => <div key={label} className="rounded-2xl border border-white/10 bg-zinc-950/50 p-4">{React.createElement(icon, { size: 21, className: 'text-amber-400' })}<p className="mt-5 text-sm font-semibold text-zinc-200">{label}</p></div>)}</div></div></div></section>
      <section id="leadership" className="scroll-mt-20 px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-7xl"><Heading eyebrow="02 — Leadership" title="Work with a clear purpose." copy="Building thoughtful structures for sustainable adoption, from grassroots communities to global partnerships." /><div className="mt-12 grid gap-5 md:grid-cols-2"><Role icon={Globe2} title="President" organization="Stellar East Africa" copy="Guiding the strategic growth of Stellar’s ecosystem across East Africa—fostering partnerships, adoption, and tools that work for local communities." /><Role icon={BriefcaseBusiness} title="Founder & CEO" organization="Zu’Co Ltd" copy="Developing blockchain solutions and advisory services that help African businesses embrace digital transformation and financial inclusion." /></div><div className="mt-5 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-3">{focusAreas.map(([title, copy]) => <div key={title} className="bg-zinc-950 p-6"><p className="text-sm font-bold text-amber-400">{title}</p><p className="mt-3 text-sm leading-6 text-zinc-500">{copy}</p></div>)}</div></div></section>
      <section id="impact" className="scroll-mt-20 border-y border-white/10 bg-white/[.025] px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-7xl"><Heading eyebrow="03 — Impact" title="Turning access into opportunity." copy="A growing body of work focused on making emerging technology useful, accessible, and locally relevant." /><div className="mt-12 grid gap-4 sm:grid-cols-3">{[['1,000+', 'Developers trained'], ['50+', 'Partnerships formed'], ['10', 'Countries reached']].map(([number, label]) => <div key={label} className="rounded-2xl border border-white/10 bg-zinc-950/60 p-7"><p className="text-4xl font-semibold tracking-tight text-amber-400 sm:text-5xl">{number}</p><p className="mt-2 text-sm text-zinc-400">{label}</p></div>)}</div><div className="mt-10 grid gap-4 lg:grid-cols-3">{impacts.map(([title, copy], index) => <article key={title} className="group rounded-2xl border border-white/10 p-6 transition hover:border-amber-400/50 hover:bg-amber-400/[.03]"><p className="text-xs font-bold tracking-widest text-amber-400">0{index + 1}</p><h3 className="mt-8 text-xl font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{copy}</p></article>)}</div></div></section>
      <section id="contact" className="scroll-mt-20 px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-4xl rounded-[2rem] border border-amber-400/20 bg-gradient-to-br from-amber-400/[.10] to-zinc-950 p-7 text-center sm:p-12"><p className="text-xs font-bold uppercase tracking-[.23em] text-amber-400">04 — Connect</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-semibold tracking-[-.05em] text-white sm:text-5xl">Let’s build the future together.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-zinc-400 sm:text-lg">Open to conversations around blockchain adoption, partnerships, speaking, mentorship, and new possibilities for East Africa.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="mailto:sarahwahinya1@gmail.com" className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-amber-400 px-6 text-sm font-bold text-zinc-950 transition hover:bg-amber-300"><Mail size={17} /> Email Sarah</a><a href="https://linkedin.com/in/sarah-wahinya" target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-white/15 px-6 text-sm font-semibold text-white transition hover:bg-white/5"><Linkedin size={17} /> LinkedIn</a><a href="https://x.com/sarahwahinya" target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-white/15 px-6 text-sm font-semibold text-white transition hover:bg-white/5"><XIcon size={16} /> Follow</a></div></div></section>
    </main><footer className="relative z-10 border-t border-white/10 px-5 py-7 text-center text-xs text-zinc-600">© {new Date().getFullYear()} Sarah Wahinya. Building the future of blockchain in East Africa.</footer>
  </div>;
}

function Role({ icon, title, organization, copy }) { return <article className="rounded-2xl border border-white/10 bg-zinc-950/60 p-7 transition hover:border-amber-400/50"><div className="grid h-11 w-11 place-items-center rounded-xl bg-amber-400/10 text-amber-400">{React.createElement(icon, { size: 22 })}</div><p className="mt-7 text-sm font-semibold text-amber-400">{organization}</p><h3 className="mt-1 text-2xl font-semibold text-white">{title}</h3><p className="mt-4 text-sm leading-7 text-zinc-500">{copy}</p></article>; }
